import type { AppProps } from "next/app";
import { Provider } from 'react-redux';

import EditCardModal from 'components/EditCard';
import Head from 'next/head';

import store from '../redux/store';

import 'antd/dist/antd.css';
import '@Style/globals.scss';

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <Provider store={store}>
      <Head>
        <title>DnD</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Component {...pageProps} />

      {/* Global Modal */}
      <EditCardModal />
    </Provider>
  );
}

export default MyApp;
