import type { NextPage } from "next";
import Head from "next/head";

import styles from "@Style/Home.module.scss";
import { useAppDispatch } from "../hooks/hooks";
import { testClick } from "../redux/slices/account/accountSlice";

const Home: NextPage = () => {
  const dispatch = useAppDispatch();

  const handleClick = () => {
    dispatch(testClick());
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="text-red-500">
        <button onClick={handleClick}>測試觸發 slice and saga</button>
      </div>
    </div>
  );
};

export default Home;
